In [2]:
import pandas as pd
import numpy as np


udemy = pd.read_csv("udemy-v2.csv")
coursera = pd.read_csv("coursera-v4.csv")

In [3]:
udemy

,course_title,rating,review_count,skills_list,platform,level,duration
0,The Complete Python Bootcamp From Zero to Hero...,4.6,486391,['python programming'],udemy,0,22.0
1,The Complete 2023 Web Development Bootcamp,4.7,338555,"['javascript', 'html and css', 'react', 'postg...",udemy,0,63.0
2,The Web Developer Bootcamp 2023,4.7,266527,"['javascript', 'html and css', 'react', 'inter...",udemy,0,74.0
3,100 Days of Code: The Complete Python Pro Boot...,4.7,251585,"['python programming', 'data science', 'theore...",udemy,0,58.0
4,React - The Complete Guide 2023 (incl. React R...,4.6,199663,['react'],udemy,0,74.5
...,...,...,...,...,...,...,...
19510,Explaining the Core Theories of Econometrics,4.2,1045,['econometrics'],udemy,1,4.0
19511,Construction Methodology Basics in Civil Engin...,4.6,1025,"['estimation', 'video']",udemy,0,46.0
19512,Udemy Masters 2016: Online Course Creation - U...,4.1,1021,['customer success'],udemy,0,28.0
19513,Aerospace Engineering: Aircraft Systems and Av...,4.4,1001,['internet of things'],udemy,0,2.5
19514,Deutsch Intensiv - Intensive German Course for...,4.8,996,['internet of things'],udemy,1,10.5

In [4]:
coursera

,course_title,rating,review_count,skills_list,platform,level,duration
0,Google Cybersecurity,4.8,16400.0,"['Network Security', 'Python Programming', 'Li...",coursera,1,78.21
1,Google Data Analytics,4.8,133400.0,"['Data Analysis', 'R Programming', 'SQL', 'Bus...",coursera,1,78.21
2,Google Project Management:,4.8,97300.0,"['Project Management', 'Strategy and Operation...",coursera,1,78.21
3,Google Digital Marketing & E-commerce,4.8,21400.0,"['Digital Marketing', 'Marketing', 'Marketing ...",coursera,1,78.21
4,Google IT Support,4.8,181400.0,"['Computer Networking', 'Network Architecture'...",coursera,1,78.21
...,...,...,...,...,...,...,...
884,Interviewing and Resume Writing in English,4.6,710.0,"['Communication', 'Human Resources', 'Strategy...",coursera,2,78.21
885,Strategic Sales Management,4.5,427.0,"['Sales', 'Marketing', 'Strategy', 'Leadership...",coursera,2,78.21
886,Essentials of Corporate Finance,4.6,1800.0,"['Finance', 'Investment Management', 'Financia...",coursera,2,78.21
887,Innovation: From Creativity to Entrepreneurship,4.8,3200.0,"['Entrepreneurship', 'Leadership and Managemen...",coursera,1,78.21
888,Excel for Beginners: Pivot Tables,4.6,52.0,['Microsoft Excel'],coursera,1,2.00

In [5]:
udemy["duration"] = udemy["duration"].astype(float)
coursera["duration"] = coursera["duration"].astype(float)

udemy["review_count"] = udemy["review_count"].astype(float)
coursera["review_count"] = coursera["review_count"].astype(float)

udemy["level"] = udemy["level"].astype(int)
coursera["level"] = coursera["level"].astype(int)

In [6]:
udemy

,course_title,rating,review_count,skills_list,platform,level,duration
0,The Complete Python Bootcamp From Zero to Hero...,4.6,486391.0,['python programming'],udemy,0,22.0
1,The Complete 2023 Web Development Bootcamp,4.7,338555.0,"['javascript', 'html and css', 'react', 'postg...",udemy,0,63.0
2,The Web Developer Bootcamp 2023,4.7,266527.0,"['javascript', 'html and css', 'react', 'inter...",udemy,0,74.0
3,100 Days of Code: The Complete Python Pro Boot...,4.7,251585.0,"['python programming', 'data science', 'theore...",udemy,0,58.0
4,React - The Complete Guide 2023 (incl. React R...,4.6,199663.0,['react'],udemy,0,74.5
...,...,...,...,...,...,...,...
19510,Explaining the Core Theories of Econometrics,4.2,1045.0,['econometrics'],udemy,1,4.0
19511,Construction Methodology Basics in Civil Engin...,4.6,1025.0,"['estimation', 'video']",udemy,0,46.0
19512,Udemy Masters 2016: Online Course Creation - U...,4.1,1021.0,['customer success'],udemy,0,28.0
19513,Aerospace Engineering: Aircraft Systems and Av...,4.4,1001.0,['internet of things'],udemy,0,2.5
19514,Deutsch Intensiv - Intensive German Course for...,4.8,996.0,['internet of things'],udemy,1,10.5

In [7]:
coursera

,course_title,rating,review_count,skills_list,platform,level,duration
0,Google Cybersecurity,4.8,16400.0,"['Network Security', 'Python Programming', 'Li...",coursera,1,78.21
1,Google Data Analytics,4.8,133400.0,"['Data Analysis', 'R Programming', 'SQL', 'Bus...",coursera,1,78.21
2,Google Project Management:,4.8,97300.0,"['Project Management', 'Strategy and Operation...",coursera,1,78.21
3,Google Digital Marketing & E-commerce,4.8,21400.0,"['Digital Marketing', 'Marketing', 'Marketing ...",coursera,1,78.21
4,Google IT Support,4.8,181400.0,"['Computer Networking', 'Network Architecture'...",coursera,1,78.21
...,...,...,...,...,...,...,...
884,Interviewing and Resume Writing in English,4.6,710.0,"['Communication', 'Human Resources', 'Strategy...",coursera,2,78.21
885,Strategic Sales Management,4.5,427.0,"['Sales', 'Marketing', 'Strategy', 'Leadership...",coursera,2,78.21
886,Essentials of Corporate Finance,4.6,1800.0,"['Finance', 'Investment Management', 'Financia...",coursera,2,78.21
887,Innovation: From Creativity to Entrepreneurship,4.8,3200.0,"['Entrepreneurship', 'Leadership and Managemen...",coursera,1,78.21
888,Excel for Beginners: Pivot Tables,4.6,52.0,['Microsoft Excel'],coursera,1,2.00

<h1>Combining 2 datasets:</h1>

In [8]:
combined_df = pd.concat([coursera, udemy], ignore_index=True)
combined_df

,course_title,rating,review_count,skills_list,platform,level,duration
0,Google Cybersecurity,4.8,16400.0,"['Network Security', 'Python Programming', 'Li...",coursera,1,78.21
1,Google Data Analytics,4.8,133400.0,"['Data Analysis', 'R Programming', 'SQL', 'Bus...",coursera,1,78.21
2,Google Project Management:,4.8,97300.0,"['Project Management', 'Strategy and Operation...",coursera,1,78.21
3,Google Digital Marketing & E-commerce,4.8,21400.0,"['Digital Marketing', 'Marketing', 'Marketing ...",coursera,1,78.21
4,Google IT Support,4.8,181400.0,"['Computer Networking', 'Network Architecture'...",coursera,1,78.21
...,...,...,...,...,...,...,...
20399,Explaining the Core Theories of Econometrics,4.2,1045.0,['econometrics'],udemy,1,4.00
20400,Construction Methodology Basics in Civil Engin...,4.6,1025.0,"['estimation', 'video']",udemy,0,46.00
20401,Udemy Masters 2016: Online Course Creation - U...,4.1,1021.0,['customer success'],udemy,0,28.00
20402,Aerospace Engineering: Aircraft Systems and Av...,4.4,1001.0,['internet of things'],udemy,0,2.50
20403,Deutsch Intensiv - Intensive German Course for...,4.8,996.0,['internet of things'],udemy,1,10.50

In [9]:
combined_df.to_csv('All-courses.csv', index=False)

<h2>Fix the Skills Seperation:</h2>

In [13]:
import ast

def fix_skills(x):
    if isinstance(x, str):
        # convert "['a', 'b']" → ['a','b']
        try:
            x = ast.literal_eval(x)
        except:
            return []
    return x
combined_df["skills_list"] = combined_df["skills_list"].apply(fix_skills)

In [14]:
def split_embedded_lists(lst):
    cleaned = []
    for item in lst:
        if isinstance(item, str) and "," in item:
            parts = [p.strip() for p in item.split(",")]
            cleaned.extend(parts)
        else:
            cleaned.append(item)
    return cleaned

combined_df["skills_list"] = combined_df["skills_list"].apply(split_embedded_lists)

In [20]:
def clean_skills_list(skills):
    """
    Flatten nested lists and remove extra spaces, lowercasing all skills.
    """
    cleaned = []
    for s in skills:
        if isinstance(s, list):
            # Flatten inner lists
            for item in s:
                cleaned.append(item.strip().lower())
        elif isinstance(s, str):
            # Some entries may be a single string with commas
            # Split by comma if needed
            parts = s.split(',')
            for p in parts:
                cleaned.append(p.strip().lower())
    # Remove duplicates
    return list(set(cleaned))

# Apply function to skills_list
combined_df['skills_list'] = combined_df['skills_list'].apply(clean_skills_list)
combined_df

,course_title,rating,review_count,skills_list,platform,level,duration
0,Google Cybersecurity,4.8,16400.0,"[databases, network architecture, risk managem...",coursera,1,78.21
1,Google Data Analytics,4.8,133400.0,"[data visualization software, small data, big ...",coursera,1,78.21
2,Google Project Management:,4.8,97300.0,"[risk management, influencing, change manageme...",coursera,1,78.21
3,Google Digital Marketing & E-commerce,4.8,21400.0,"[social media, media strategy & planning, web ...",coursera,1,78.21
4,Google IT Support,4.8,181400.0,"[network security, network analysis, cloud com...",coursera,1,78.21
...,...,...,...,...,...,...,...
20399,Explaining the Core Theories of Econometrics,4.2,1045.0,[econometrics],udemy,1,4.00
20400,Construction Methodology Basics in Civil Engin...,4.6,1025.0,"[estimation, video]",udemy,0,46.00
20401,Udemy Masters 2016: Online Course Creation - U...,4.1,1021.0,[customer success],udemy,0,28.00
20402,Aerospace Engineering: Aircraft Systems and Av...,4.4,1001.0,[internet of things],udemy,0,2.50
20403,Deutsch Intensiv - Intensive German Course for...,4.8,996.0,[internet of things],udemy,1,10.50

In [21]:
combined_df.to_csv('All-courses.csv', index=False)