In [118]:
import pandas as pd
import numpy as np

In [119]:
udemy = pd.read_csv("Udemy.csv")
udemy

,title,description,instructor,rating,reviewcount,duration,lectures,level
0,The Complete Python Bootcamp From Zero to Hero...,Learn Python like a Professional Start from t...,Jose Portilla,4.6,486391,22 total hours,156 lectures,All Levels
1,The Complete 2023 Web Development Bootcamp,Become a Full-Stack Web Developer with just ON...,Dr. Angela Yu,4.7,338555,63 total hours,380 lectures,All Levels
2,The Web Developer Bootcamp 2023,10 Hours of React just added. Become a Develop...,Colt Steele,4.7,266527,74 total hours,722 lectures,All Levels
3,100 Days of Code: The Complete Python Pro Boot...,Master Python by building 100 projects in 100 ...,Dr. Angela Yu,4.7,251585,58 total hours,636 lectures,All Levels
4,React - The Complete Guide 2023 (incl. React R...,Dive in and learn React.js from scratch! Learn...,"Academind by Maximilian Schwarzmüller, Maximil...",4.6,199663,74.5 total hours,739 lectures,All Levels
...,...,...,...,...,...,...,...,...
26251,Business English for Meetings,Useful English Phrases for Communicating with ...,Kendra Lucas,4.6,1015,1.5 total hours,27 lectures,Intermediate
26252,Aerospace Engineering: Aircraft Systems and Av...,Aerospace and Aeronautical Engineering: Master...,Lluís Foreman - ValueKnow,4.4,1001,2.5 total hours,19 lectures,All Levels
26253,Forensic Psychology : Criminal Profiling Certi...,Criminology Crash Course,Ahilan Chandran,4.4,1002,3 total hours,47 lectures,Beginner
26254,Deutsch Intensiv - Intensive German Course for...,Master all the ins and outs of the German lang...,Kamil Pakula,4.8,996,10.5 total hours,112 lectures,Beginner
26255,Renewable Energy and Sustainable Development,Environmental Issues,Telly Frias Jr,4.2,995,2 total hours,30 lectures,Beginner

In [120]:
udemy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26256 entries, 0 to 26255
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        26256 non-null  object
 1   description  26252 non-null  object
 2   instructor   26256 non-null  object
 3   rating       26256 non-null  float64
 4   reviewcount  26256 non-null  int64
 5   duration     26256 non-null  object
 6   lectures     26255 non-null  object
 7   level        25889 non-null  object
dtypes: float64(1), int64(1), object(6)
memory usage: 1.6+ MB

In [121]:
#Droping 'instructor','lectures' columns from data because it'll not be useful in tranining
try:
    udemy = udemy.drop(['instructor','lectures'],axis=1)
except Exception as ex:
    print("Data has been already processed")
udemy

,title,description,rating,reviewcount,duration,level
0,The Complete Python Bootcamp From Zero to Hero...,Learn Python like a Professional Start from t...,4.6,486391,22 total hours,All Levels
1,The Complete 2023 Web Development Bootcamp,Become a Full-Stack Web Developer with just ON...,4.7,338555,63 total hours,All Levels
2,The Web Developer Bootcamp 2023,10 Hours of React just added. Become a Develop...,4.7,266527,74 total hours,All Levels
3,100 Days of Code: The Complete Python Pro Boot...,Master Python by building 100 projects in 100 ...,4.7,251585,58 total hours,All Levels
4,React - The Complete Guide 2023 (incl. React R...,Dive in and learn React.js from scratch! Learn...,4.6,199663,74.5 total hours,All Levels
...,...,...,...,...,...,...
26251,Business English for Meetings,Useful English Phrases for Communicating with ...,4.6,1015,1.5 total hours,Intermediate
26252,Aerospace Engineering: Aircraft Systems and Av...,Aerospace and Aeronautical Engineering: Master...,4.4,1001,2.5 total hours,All Levels
26253,Forensic Psychology : Criminal Profiling Certi...,Criminology Crash Course,4.4,1002,3 total hours,Beginner
26254,Deutsch Intensiv - Intensive German Course for...,Master all the ins and outs of the German lang...,4.8,996,10.5 total hours,Beginner
26255,Renewable Energy and Sustainable Development,Environmental Issues,4.2,995,2 total hours,Beginner

<h1>Data Featuring</h1>

In [122]:
#Normalization of the column names
try:
    udemy = udemy.rename(
        columns={
            "title": "course_title",
            "reviewcount": "review_count"
        }
    )
except:
    print("columns has been changing")
udemy

,course_title,description,rating,review_count,duration,level
0,The Complete Python Bootcamp From Zero to Hero...,Learn Python like a Professional Start from t...,4.6,486391,22 total hours,All Levels
1,The Complete 2023 Web Development Bootcamp,Become a Full-Stack Web Developer with just ON...,4.7,338555,63 total hours,All Levels
2,The Web Developer Bootcamp 2023,10 Hours of React just added. Become a Develop...,4.7,266527,74 total hours,All Levels
3,100 Days of Code: The Complete Python Pro Boot...,Master Python by building 100 projects in 100 ...,4.7,251585,58 total hours,All Levels
4,React - The Complete Guide 2023 (incl. React R...,Dive in and learn React.js from scratch! Learn...,4.6,199663,74.5 total hours,All Levels
...,...,...,...,...,...,...
26251,Business English for Meetings,Useful English Phrases for Communicating with ...,4.6,1015,1.5 total hours,Intermediate
26252,Aerospace Engineering: Aircraft Systems and Av...,Aerospace and Aeronautical Engineering: Master...,4.4,1001,2.5 total hours,All Levels
26253,Forensic Psychology : Criminal Profiling Certi...,Criminology Crash Course,4.4,1002,3 total hours,Beginner
26254,Deutsch Intensiv - Intensive German Course for...,Master all the ins and outs of the German lang...,4.8,996,10.5 total hours,Beginner
26255,Renewable Energy and Sustainable Development,Environmental Issues,4.2,995,2 total hours,Beginner

<h3>Handling the Missing values</h3>

In [123]:
#the null values insights
udemy.isna().sum()

course_title      0
description       4
rating            0
review_count      0
duration          0
level           367
dtype: int64

In [124]:
udemy = udemy.dropna(subset=['description'])
udemy = udemy.dropna(subset=['level'])
udemy.isna().sum()

course_title    0
description     0
rating          0
review_count    0
duration        0
level           0
dtype: int64

In [125]:
udemy.to_csv('udemy-v1.csv', index=False)

<h3>Creating a skill coulmn from the description coulmn</h3>

In [126]:
udemy_v1 = pd.read_csv("udemy-v1.csv")
udemy_v1

,course_title,description,rating,review_count,duration,level
0,The Complete Python Bootcamp From Zero to Hero...,Learn Python like a Professional Start from t...,4.6,486391,22 total hours,All Levels
1,The Complete 2023 Web Development Bootcamp,Become a Full-Stack Web Developer with just ON...,4.7,338555,63 total hours,All Levels
2,The Web Developer Bootcamp 2023,10 Hours of React just added. Become a Develop...,4.7,266527,74 total hours,All Levels
3,100 Days of Code: The Complete Python Pro Boot...,Master Python by building 100 projects in 100 ...,4.7,251585,58 total hours,All Levels
4,React - The Complete Guide 2023 (incl. React R...,Dive in and learn React.js from scratch! Learn...,4.6,199663,74.5 total hours,All Levels
...,...,...,...,...,...,...
25880,Business English for Meetings,Useful English Phrases for Communicating with ...,4.6,1015,1.5 total hours,Intermediate
25881,Aerospace Engineering: Aircraft Systems and Av...,Aerospace and Aeronautical Engineering: Master...,4.4,1001,2.5 total hours,All Levels
25882,Forensic Psychology : Criminal Profiling Certi...,Criminology Crash Course,4.4,1002,3 total hours,Beginner
25883,Deutsch Intensiv - Intensive German Course for...,Master all the ins and outs of the German lang...,4.8,996,10.5 total hours,Beginner
25884,Renewable Energy and Sustainable Development,Environmental Issues,4.2,995,2 total hours,Beginner

In [127]:
import re
from collections import Counter, defaultdict

#read the coursera skills
SKILLS_FILE = "coursera_skills_list.txt"

# tokens that are generic stopwords regardless of frequency (extend if needed)
GLOBAL_GENERIC_TOKENS = {
    "programming","development","management","analysis","design","operations",
    "software","systems","data","business","project","principles","theory",
    "applications","tools","methods","practice","basics","models","model",
    "general","techniques","statistics","statistical","planning","research",
    "training","learning","skills","engineering","visualization","visual",
    "web","cloud","process","product"
}

In [128]:
# string cleaning helper functions:
def clean_text(text):
    """Lowercase, remove punctuation (keep +.#), collapse spaces."""
    text = str(text).lower()
    text = re.sub(r"[^a-z0-9+.# ]", " ", text)
    return re.sub(r"\s+", " ", text).strip()

def normalize_skill_name(s):
    """Normalize single skill entry: remove parenthesis notes and extra spaces."""
    s = str(s).strip()
    # remove surrounding quotes/braces if any
    s = re.sub(r'^[\[\{"\']+|[\]\},"\']+$', '', s).strip()
    # remove parenthetical clarifiers like "react (web framework)" -> "react"
    s = re.sub(r'\([^)]*\)', '', s)
    s = re.sub(r'\s+', ' ', s).strip()
    return s.lower()

In [129]:
# load the skills and clean them:
with open(SKILLS_FILE, "r", encoding="utf-8") as f:
    raw_skills = [line.strip() for line in f if line.strip()]

# normalize and deduplicate
skill_list = []
orig_map = {}   # map normalized -> original (for readability)
for s in raw_skills:
    norm = normalize_skill_name(s)
    if norm and norm not in skill_list:
        skill_list.append(norm)
        orig_map[norm] = s

print(f"Loaded {len(skill_list)} unique normalized skills.")

Loaded 349 unique normalized skills.

In [130]:
# TOKEN FREQUENCIES (across skill list)
token_counts = Counter()
skill_tokens_map = {}
for skill in skill_list:
    toks = skill.split()
    skill_tokens_map[skill] = toks
    token_counts.update(toks)

# choose threshold to call a token 'generic' by frequency across skill list
# (tweak threshold depending on how large the skill list is; 6 is a good starting point)
GENERIC_TOKEN_FREQ_THRESHOLD = 6

# build generic token set = globally generic + frequent tokens
freq_generic_tokens = {tok for tok, cnt in token_counts.items() if cnt >= GENERIC_TOKEN_FREQ_THRESHOLD}
generic_tokens = set(GLOBAL_GENERIC_TOKENS) | freq_generic_tokens

# build core tokens (tokens considered informative)
core_tokens_map = {}
for skill, toks in skill_tokens_map.items():
    core = [t for t in toks if t not in generic_tokens]
    core_tokens_map[skill] = core

# Find skills that are problematic (no core tokens) -> we will drop or flag them
no_core_skills = [s for s, core in core_tokens_map.items() if len(core) == 0]
print(f"Skills with NO core tokens (will be flagged/dropped): {len(no_core_skills)}")
# print(no_core_skills[:50])

# Optional: drop or keep minimal list - here we remove them from skill_list to avoid spamming matches
safe_skill_list = [s for s in skill_list if s not in no_core_skills]
safe_skill_list = [s for s in safe_skill_list if s not in ["software as a service", "professional development"]]
print(f"Using {len(safe_skill_list)} skills after removing overly-generic ones.")

Skills with NO core tokens (will be flagged/dropped): 62
Using 285 skills after removing overly-generic ones.

In [131]:
# Matching function
def match_skill(skill, desc_words_set, desc_text, core_tokens_map=core_tokens_map):
    """
    Return True if skill matches the description represented by desc_words_set and desc_text.
    Rules:
     - Exact phrase match wins.
     - Else, require at least one core token present.
     - If skill has multiple tokens: require either exact phrase or (>=1 core token AND >=1 other token match)
     - Single-token skills: require that token (it is a core token) present in text words.
    """
    skill_text = skill  # already normalized
    # exact phrase
    if re.search(r"\b" + re.escape(skill_text) + r"\b", desc_text):
        return True

    tokens = skill_tokens_map[skill_text]
    core_tokens = core_tokens_map.get(skill_text, [])

    # if no core tokens, don't match (we removed them earlier but keep check)
    if not core_tokens:
        return False

    # presence of any core token in description
    core_present = any(tok in desc_words_set for tok in core_tokens)
    if not core_present:
        return False

    # if single-token skill (e.g., 'python' or 'react'), core_present is enough
    if len(tokens) == 1:
        return True

    # for multi-token skill: require additional evidence:
    # either the exact phrase (already checked) OR at least one other token (core or non-generic)
    other_tokens = [t for t in tokens if t not in core_tokens] + [t for t in tokens if t in core_tokens]
    # remove duplicates
    other_tokens = list(dict.fromkeys(other_tokens))

    # check if any other token (excluding the matched core token) is present
    # (we'll just check if any token besides the core appears; this is conservative)
    # Actually require at least one token from tokens besides the core_tokens that matched core token.
    other_present = any(tok in desc_words_set for tok in tokens if tok in desc_words_set and tok not in generic_tokens)

    # fallback: if other_present is False, but there are >=2 core tokens and at least 2 core tokens are present -> accept
    core_count_in_desc = sum(1 for tok in core_tokens if tok in desc_words_set)
    if other_present or core_count_in_desc >= 2:
        return True

    return False

def extract_skills_from_text(desc_text):
    desc = clean_text(desc_text)
    words = set(desc.split())
    matches = []
    for skill in safe_skill_list:
        try:
            if match_skill(skill, words, desc):
                matches.append(skill)
        except Exception as e:
            # just in case; won't break pipeline
            continue
    return matches

In [132]:
#SANITY CHECK using 3 courses from Udemy
sample = [
    {
      "course_title":"The Complete Python Bootcamp From Zero to Hero in Python",
      "description":"Learn Python like a Professional  Start from the basics and go all the way to creating your own applications and games"
    },
    {
      "course_title":"The Complete 2023 Web Development Bootcamp",
      "description":"Become a Full-Stack Web Developer with just ONE course. HTML, CSS, Javascript, Node, React, PostgreSQL, Web3 and DApps"
    },
    {
      "course_title":"The Web Developer Bootcamp 2023",
      "description":"10 Hours of React just added. Become a Developer With ONE course - HTML, CSS, JavaScript, React, Node, MongoDB and More!"
    }
]

for r in sample:
    print("TITLE:", r["course_title"])
    print("DESC:", r["description"])
    print("MATCHED SKILLS:", extract_skills_from_text(r["description"]))
    print("-"*60)

TITLE: The Complete Python Bootcamp From Zero to Hero in Python
DESC: Learn Python like a Professional  Start from the basics and go all the way to creating your own applications and games
MATCHED SKILLS: ['python programming']
------------------------------------------------------------
TITLE: The Complete 2023 Web Development Bootcamp
DESC: Become a Full-Stack Web Developer with just ONE course. HTML, CSS, Javascript, Node, React, PostgreSQL, Web3 and DApps
MATCHED SKILLS: ['javascript', 'html and css', 'react', 'postgresql']
------------------------------------------------------------
TITLE: The Web Developer Bootcamp 2023
DESC: 10 Hours of React just added. Become a Developer With ONE course - HTML, CSS, JavaScript, React, Node, MongoDB and More!
MATCHED SKILLS: ['javascript', 'html and css', 'react', 'internet of things']
------------------------------------------------------------

In [133]:
# APPLY to full Udemy file
udemy_v1["skills"] = udemy_v1["description"].apply(extract_skills_from_text)

In [134]:
udemy_v1

,course_title,description,rating,review_count,duration,level,skills
0,The Complete Python Bootcamp From Zero to Hero...,Learn Python like a Professional Start from t...,4.6,486391,22 total hours,All Levels,[python programming]
1,The Complete 2023 Web Development Bootcamp,Become a Full-Stack Web Developer with just ON...,4.7,338555,63 total hours,All Levels,"[javascript, html and css, react, postgresql]"
2,The Web Developer Bootcamp 2023,10 Hours of React just added. Become a Develop...,4.7,266527,74 total hours,All Levels,"[javascript, html and css, react, internet of ..."
3,100 Days of Code: The Complete Python Pro Boot...,Master Python by building 100 projects in 100 ...,4.7,251585,58 total hours,All Levels,"[python programming, data science, theoretical..."
4,React - The Complete Guide 2023 (incl. React R...,Dive in and learn React.js from scratch! Learn...,4.6,199663,74.5 total hours,All Levels,[react]
...,...,...,...,...,...,...,...
25880,Business English for Meetings,Useful English Phrases for Communicating with ...,4.6,1015,1.5 total hours,Intermediate,[]
25881,Aerospace Engineering: Aircraft Systems and Av...,Aerospace and Aeronautical Engineering: Master...,4.4,1001,2.5 total hours,All Levels,[internet of things]
25882,Forensic Psychology : Criminal Profiling Certi...,Criminology Crash Course,4.4,1002,3 total hours,Beginner,[]
25883,Deutsch Intensiv - Intensive German Course for...,Master all the ins and outs of the German lang...,4.8,996,10.5 total hours,Beginner,[internet of things]
25884,Renewable Energy and Sustainable Development,Environmental Issues,4.2,995,2 total hours,Beginner,[]

<h4>DIAGNOSTICS:</h4>

In [135]:
# 1) rows with empty skills:
udemy_v1[udemy_v1["skills"].apply(len)==0]

,course_title,description,rating,review_count,duration,level,skills
11,Automate the Boring Stuff with Python Programming,A practical programming course for office work...,4.6,110425,9.5 total hours,All Levels,[]
19,"[NEW] Spring Boot 3, Spring 6 & Hibernate for ...","Spring Boot 3: Learn Spring 6, Spring Core, Sp...",4.6,76775,33.5 total hours,All Levels,[]
21,The Complete Node.js Developer Course (3rd Edi...,Learn Node.js by building real-world applicati...,4.5,70853,35 total hours,All Levels,[]
56,Master the Coding Interview: Data Structures +...,Ultimate coding interview bootcamp. Get more j...,4.7,33658,20 total hours,All Levels,[]
58,The Complete ASP.NET MVC 5 Course,Learn to build fast and secure web application...,4.4,33603,7.5 total hours,All Levels,[]
...,...,...,...,...,...,...,...
25877,OFF-GRID Solar Energy Systems: Design and Oper...,[HIGHEST RATED] Taught by an Energy Engineer -...,4.5,1022,3 total hours,All Levels,[]
25879,Formal Email Writing - Business English,Quickly and easily learn how to write formal e...,4.7,1016,2.5 total hours,Intermediate,[]
25880,Business English for Meetings,Useful English Phrases for Communicating with ...,4.6,1015,1.5 total hours,Intermediate,[]
25882,Forensic Psychology : Criminal Profiling Certi...,Criminology Crash Course,4.4,1002,3 total hours,Beginner,[]
25884,Renewable Energy and Sustainable Development,Environmental Issues,4.2,995,2 total hours,Beginner,[]

In [136]:
# 2) which skills are most commonly matched:
from collections import Counter
Counter(x for row in udemy_v1["skills"] for x in row).most_common(60)

[('internet of things', 4360),
 ('microsoft excel', 1241),
 ('python programming', 1213),
 ('google app engine', 1082),
 ('securities trading', 1052),
 ('microsoft azure', 887),
 ('database application', 767),
 ('financial analysis', 679),
 ('financial accounting', 679),
 ('financial management', 679),
 ('javascript', 625),
 ('google cloud platform', 579),
 ('machine learning algorithms', 578),
 ('c programming language family', 546),
 ('java programming', 541),
 ('natural language processing', 535),
 ('basic descriptive statistics', 512),
 ('power bi', 502),
 ('cloud api', 497),
 ('sql', 493),
 ('applied machine learning', 487),
 ('user experience', 487),
 ('user experience design', 487),
 ('media strategy & planning', 480),
 ('application development', 472),
 ('machine learning', 455),
 ('machine learning software', 455),
 ('statistical machine learning', 455),
 ('game theory', 452),
 ('system security', 438),
 ('system software', 438),
 ('system programming', 438),
 ('html and css', 432),
 ('react', 431),
 ('theoretical computer science', 412),
 ('data science', 402),
 ('amazon web services', 397),
 ('computer science', 394),
 ('strategy', 390),
 ('database administration', 385),
 ('market analysis', 383),
 ('market research', 383),
 ('software testing', 370),
 ('website', 365),
 ('strategy and operations', 364),
 ('product strategy', 364),
 ('security strategy', 364),
 ('android development', 361),
 ('technical product management', 358),
 ('aws', 342),
 ('c# programming', 335),
 ('database design', 313),
 ('database theory', 313),
 ('customer success', 311),
 ('php programming', 310),
 ('finance', 305),
 ('sap', 303),
 ('network architecture', 297),
 ('entrepreneurial finance', 297),
 ('video', 296)]

<h4>Handling the empty skill list for some courses</h4>
<p>keep them commented to not ruin the data</p>

In [137]:
'''
# get descriptions with empty skills
empty_desc = udemy_v1[udemy_v1["skills"].apply(len) == 0]["description"]

from collections import Counter
all_words = Counter()
for d in empty_desc:
    all_words.update(clean_text(d).split())

# see top 150 words
print(all_words.most_common(150))
'''

[('to', 3801), ('and', 3249), ('learn', 2110), ('the', 1809), ('a', 1676), ('your', 1464), ('with', 1285), ('how', 1213), ('for', 1179), ('in', 1154), ('course', 885), ('you', 830), ('from', 756), ('on', 605), ('by', 599), ('step', 565), ('guide', 445), ('business', 422), ('this', 416), ('using', 396), ('build', 360), ('an', 356), ('get', 347), ('complete', 345), ('create', 335), ('become', 329), ('master', 312), ('more', 299), ('use', 299), ('that', 267), ('skills', 257), ('management', 246), ('data', 240), ('web', 231), ('real', 230), ('need', 230), ('practical', 229), ('is', 220), ('make', 216), ('professional', 215), ('about', 206), ('all', 205), ('start', 204), ('project', 201), ('will', 198), ('advanced', 197), ('beginners', 192), ('or', 188), ('design', 187), ('training', 186), ('easy', 180), ('it', 177), ('online', 173), ('s', 171), ('everything', 169), ('can', 169), ('scratch', 168), ('be', 168), ('exam', 167), ('world', 161), ('learning', 159), ('beginner', 159), ('own', 158), ('techniques', 158), ('know', 157), ('certification', 155), ('level', 154), ('as', 152), ('accounting', 152), ('time', 146), ('like', 145), ('building', 142), ('best', 142), ('programming', 141), ('development', 139), ('life', 139), ('way', 138), ('expert', 132), ('comprehensive', 131), ('applications', 129), ('projects', 127), ('analysis', 119), ('work', 119), ('new', 117), ('hands', 117), ('pro', 116), ('strategies', 116), ('sales', 115), ('take', 114), ('software', 114), ('what', 111), ('understand', 109), ('simple', 109), ('up', 108), ('code', 106), ('tools', 103), ('security', 100), ('better', 98), ('improve', 97), ('write', 97), ('trade', 95), ('most', 94), ('help', 94), ('career', 93), ('examples', 93), ('no', 92), ('quickbooks', 91), ('through', 90), ('income', 90), ('marketing', 90), ('concepts', 89), ('process', 88), ('creating', 88), ('3', 86), ('manage', 86), ('earn', 85), ('effective', 85), ('2', 84), ('at', 84), ('1', 84), ('certified', 83), ('fast', 82), ('framework', 82), ('started', 82), ('without', 80), ('basics', 80), ('develop', 79), ('free', 79), ('bookkeeping', 79), ('any', 78), ('first', 78), ('core', 77), ('next', 77), ('into', 77), ('successful', 77), ('are', 76), ('practice', 75), ('great', 75), ('full', 74), ('based', 74), ('automation', 73), ('one', 73), ('5', 72), ('quickly', 72), ('facebook', 70), ('job', 69), ('knowledge', 69), ('test', 69), ('+', 69), ('go', 68)]

In [138]:
'''
#filter the unwated words:
STOPWORDS = set([
    "to","and","learn","the","a","your","with","in","how","for","course",
    "you","from","by","step","on","guide","using","this","that","is","an",
    "all","will","about","or","s","it","as","be","can","no","up","new","take",
    "easy","own","get","more","know","best","pro","hands","level","way","build","create","complete","become",
    "use","skills","start","practical","need","real","comprehensive","understand","projects","training",
    "world","online","exam","techniques","code","everything","master","advanced","work","professional","management",
    "make","beginners","project","scratch","programming","learning","beginner","certification","development",
    "building","time","like","applications", "life", "expert", "simple","framework","most","analysis","tools",
    "strategies","what","write","examples","creating","certified","help","free","better","improve","career","manage",
    "process","fast","without","basics","at","through","concepts","trade","income","practice","first","develop","any",
    "into","core","earn","quickbooks","2","3","1","effective","coding","quickly","next","started","+","websites","full"
    ,"one","based"
])

# Filter top tokens
valuable_tokens = [(tok, cnt) for tok, cnt in all_words.most_common(150) if tok not in STOPWORDS]
print(valuable_tokens)
'''

[('business', 422), ('data', 240), ('web', 231), ('design', 187), ('accounting', 152), ('sales', 115), ('software', 114), ('security', 100), ('marketing', 90), ('bookkeeping', 79), ('successful', 77), ('are', 76), ('great', 75), ('automation', 73), ('5', 72), ('facebook', 70), ('job', 69), ('knowledge', 69), ('test', 69), ('go', 68)]

In [139]:
'''
# add the remaining words to the skills file 
#(when overlap add to the old python ==> python programming)
new_skills = []
for tok, _ in valuable_tokens:
    if tok not in safe_skill_list:
        # create normalized skill name
        if tok in ['python','c#','php','java','node','spring','django']:
            new_skills.append(tok + " programming")
        else:
            new_skills.append(tok)

# add them to your skill file
with open("coursera_skills_list.txt", "a", encoding="utf-8") as f:
    for s in new_skills:
        f.write(s + "\n")
'''

In [140]:
'''
udemy_v1["skills"] = udemy_v1["description"].apply(extract_skills_from_text)
'''

In [143]:
udemy_v1

,course_title,description,rating,review_count,duration,level,skills
0,The Complete Python Bootcamp From Zero to Hero...,Learn Python like a Professional Start from t...,4.6,486391,22 total hours,All Levels,[python programming]
1,The Complete 2023 Web Development Bootcamp,Become a Full-Stack Web Developer with just ON...,4.7,338555,63 total hours,All Levels,"[javascript, html and css, react, postgresql]"
2,The Web Developer Bootcamp 2023,10 Hours of React just added. Become a Develop...,4.7,266527,74 total hours,All Levels,"[javascript, html and css, react, internet of ..."
3,100 Days of Code: The Complete Python Pro Boot...,Master Python by building 100 projects in 100 ...,4.7,251585,58 total hours,All Levels,"[python programming, data science, theoretical..."
4,React - The Complete Guide 2023 (incl. React R...,Dive in and learn React.js from scratch! Learn...,4.6,199663,74.5 total hours,All Levels,[react]
...,...,...,...,...,...,...,...
25880,Business English for Meetings,Useful English Phrases for Communicating with ...,4.6,1015,1.5 total hours,Intermediate,[]
25881,Aerospace Engineering: Aircraft Systems and Av...,Aerospace and Aeronautical Engineering: Master...,4.4,1001,2.5 total hours,All Levels,[internet of things]
25882,Forensic Psychology : Criminal Profiling Certi...,Criminology Crash Course,4.4,1002,3 total hours,Beginner,[]
25883,Deutsch Intensiv - Intensive German Course for...,Master all the ins and outs of the German lang...,4.8,996,10.5 total hours,Beginner,[internet of things]
25884,Renewable Energy and Sustainable Development,Environmental Issues,4.2,995,2 total hours,Beginner,[]

In [142]:
# 1) rows with empty skills:
udemy_v1[udemy_v1["skills"].apply(len)==0]

,course_title,description,rating,review_count,duration,level,skills
11,Automate the Boring Stuff with Python Programming,A practical programming course for office work...,4.6,110425,9.5 total hours,All Levels,[]
19,"[NEW] Spring Boot 3, Spring 6 & Hibernate for ...","Spring Boot 3: Learn Spring 6, Spring Core, Sp...",4.6,76775,33.5 total hours,All Levels,[]
21,The Complete Node.js Developer Course (3rd Edi...,Learn Node.js by building real-world applicati...,4.5,70853,35 total hours,All Levels,[]
56,Master the Coding Interview: Data Structures +...,Ultimate coding interview bootcamp. Get more j...,4.7,33658,20 total hours,All Levels,[]
58,The Complete ASP.NET MVC 5 Course,Learn to build fast and secure web application...,4.4,33603,7.5 total hours,All Levels,[]
...,...,...,...,...,...,...,...
25877,OFF-GRID Solar Energy Systems: Design and Oper...,[HIGHEST RATED] Taught by an Energy Engineer -...,4.5,1022,3 total hours,All Levels,[]
25879,Formal Email Writing - Business English,Quickly and easily learn how to write formal e...,4.7,1016,2.5 total hours,Intermediate,[]
25880,Business English for Meetings,Useful English Phrases for Communicating with ...,4.6,1015,1.5 total hours,Intermediate,[]
25882,Forensic Psychology : Criminal Profiling Certi...,Criminology Crash Course,4.4,1002,3 total hours,Beginner,[]
25884,Renewable Energy and Sustainable Development,Environmental Issues,4.2,995,2 total hours,Beginner,[]

In [144]:
# Drop rows where 'skills' list is empty
udemy_v1 = udemy_v1[udemy_v1["skills"].apply(lambda x: len(x) > 0)]

# Reset index if you want
udemy_v1.reset_index(drop=True, inplace=True)

# Check
print(udemy_v1.shape)

(19515, 7)

In [145]:
udemy_v1

,course_title,description,rating,review_count,duration,level,skills
0,The Complete Python Bootcamp From Zero to Hero...,Learn Python like a Professional Start from t...,4.6,486391,22 total hours,All Levels,[python programming]
1,The Complete 2023 Web Development Bootcamp,Become a Full-Stack Web Developer with just ON...,4.7,338555,63 total hours,All Levels,"[javascript, html and css, react, postgresql]"
2,The Web Developer Bootcamp 2023,10 Hours of React just added. Become a Develop...,4.7,266527,74 total hours,All Levels,"[javascript, html and css, react, internet of ..."
3,100 Days of Code: The Complete Python Pro Boot...,Master Python by building 100 projects in 100 ...,4.7,251585,58 total hours,All Levels,"[python programming, data science, theoretical..."
4,React - The Complete Guide 2023 (incl. React R...,Dive in and learn React.js from scratch! Learn...,4.6,199663,74.5 total hours,All Levels,[react]
...,...,...,...,...,...,...,...
19510,Explaining the Core Theories of Econometrics,This is an introductory College level economet...,4.2,1045,4 total hours,Beginner,[econometrics]
19511,Construction Methodology Basics in Civil Engin...,New Home Construction & Building construction ...,4.6,1025,46 total hours,All Levels,"[estimation, video]"
19512,Udemy Masters 2016: Online Course Creation - U...,Learn exactly how to create and sell online co...,4.1,1021,28 total hours,All Levels,[customer success]
19513,Aerospace Engineering: Aircraft Systems and Av...,Aerospace and Aeronautical Engineering: Master...,4.4,1001,2.5 total hours,All Levels,[internet of things]
19514,Deutsch Intensiv - Intensive German Course for...,Master all the ins and outs of the German lang...,4.8,996,10.5 total hours,Beginner,[internet of things]

In [149]:
try:
    udemy_v1 = udemy_v1.drop(['description'],axis=1)
except Exception as ex:
    print("Data has been already processed")
udemy_v1

Data has been already processed

,course_title,rating,review_count,duration,level,skills
0,The Complete Python Bootcamp From Zero to Hero...,4.6,486391,22 total hours,All Levels,[python programming]
1,The Complete 2023 Web Development Bootcamp,4.7,338555,63 total hours,All Levels,"[javascript, html and css, react, postgresql]"
2,The Web Developer Bootcamp 2023,4.7,266527,74 total hours,All Levels,"[javascript, html and css, react, internet of ..."
3,100 Days of Code: The Complete Python Pro Boot...,4.7,251585,58 total hours,All Levels,"[python programming, data science, theoretical..."
4,React - The Complete Guide 2023 (incl. React R...,4.6,199663,74.5 total hours,All Levels,[react]
...,...,...,...,...,...,...
19510,Explaining the Core Theories of Econometrics,4.2,1045,4 total hours,Beginner,[econometrics]
19511,Construction Methodology Basics in Civil Engin...,4.6,1025,46 total hours,All Levels,"[estimation, video]"
19512,Udemy Masters 2016: Online Course Creation - U...,4.1,1021,28 total hours,All Levels,[customer success]
19513,Aerospace Engineering: Aircraft Systems and Av...,4.4,1001,2.5 total hours,All Levels,[internet of things]
19514,Deutsch Intensiv - Intensive German Course for...,4.8,996,10.5 total hours,Beginner,[internet of things]

In [151]:
#Normalization of the column names
try:
    udemy_v1 = udemy_v1.rename(
        columns={
            "skills": "skills_list",
        }
    )
except:
    print("columns has been changing")
udemy_v1

,course_title,rating,review_count,duration,level,skills_list
0,The Complete Python Bootcamp From Zero to Hero...,4.6,486391,22 total hours,All Levels,[python programming]
1,The Complete 2023 Web Development Bootcamp,4.7,338555,63 total hours,All Levels,"[javascript, html and css, react, postgresql]"
2,The Web Developer Bootcamp 2023,4.7,266527,74 total hours,All Levels,"[javascript, html and css, react, internet of ..."
3,100 Days of Code: The Complete Python Pro Boot...,4.7,251585,58 total hours,All Levels,"[python programming, data science, theoretical..."
4,React - The Complete Guide 2023 (incl. React R...,4.6,199663,74.5 total hours,All Levels,[react]
...,...,...,...,...,...,...
19510,Explaining the Core Theories of Econometrics,4.2,1045,4 total hours,Beginner,[econometrics]
19511,Construction Methodology Basics in Civil Engin...,4.6,1025,46 total hours,All Levels,"[estimation, video]"
19512,Udemy Masters 2016: Online Course Creation - U...,4.1,1021,28 total hours,All Levels,[customer success]
19513,Aerospace Engineering: Aircraft Systems and Av...,4.4,1001,2.5 total hours,All Levels,[internet of things]
19514,Deutsch Intensiv - Intensive German Course for...,4.8,996,10.5 total hours,Beginner,[internet of things]

In [153]:
udemy_v1["platform"] = "udemy"
udemy_v1

,course_title,rating,review_count,duration,level,skills_list,platform
0,The Complete Python Bootcamp From Zero to Hero...,4.6,486391,22 total hours,All Levels,[python programming],udemy
1,The Complete 2023 Web Development Bootcamp,4.7,338555,63 total hours,All Levels,"[javascript, html and css, react, postgresql]",udemy
2,The Web Developer Bootcamp 2023,4.7,266527,74 total hours,All Levels,"[javascript, html and css, react, internet of ...",udemy
3,100 Days of Code: The Complete Python Pro Boot...,4.7,251585,58 total hours,All Levels,"[python programming, data science, theoretical...",udemy
4,React - The Complete Guide 2023 (incl. React R...,4.6,199663,74.5 total hours,All Levels,[react],udemy
...,...,...,...,...,...,...,...
19510,Explaining the Core Theories of Econometrics,4.2,1045,4 total hours,Beginner,[econometrics],udemy
19511,Construction Methodology Basics in Civil Engin...,4.6,1025,46 total hours,All Levels,"[estimation, video]",udemy
19512,Udemy Masters 2016: Online Course Creation - U...,4.1,1021,28 total hours,All Levels,[customer success],udemy
19513,Aerospace Engineering: Aircraft Systems and Av...,4.4,1001,2.5 total hours,All Levels,[internet of things],udemy
19514,Deutsch Intensiv - Intensive German Course for...,4.8,996,10.5 total hours,Beginner,[internet of things],udemy

In [157]:
# Define a common mapping
level_map = {
    "Beginner": 1,
    "Intermediate": 2,
    "Advanced": 3,
    "Expert": 4,
    "All Levels": 0
}

# Apply mapping
udemy_v1["level_num"] = udemy_v1["level"].map(level_map)

In [156]:
udemy_v1

,course_title,rating,review_count,duration,level,skills_list,platform,level_num
0,The Complete Python Bootcamp From Zero to Hero...,4.6,486391,22 total hours,All Levels,[python programming],udemy,0
1,The Complete 2023 Web Development Bootcamp,4.7,338555,63 total hours,All Levels,"[javascript, html and css, react, postgresql]",udemy,0
2,The Web Developer Bootcamp 2023,4.7,266527,74 total hours,All Levels,"[javascript, html and css, react, internet of ...",udemy,0
3,100 Days of Code: The Complete Python Pro Boot...,4.7,251585,58 total hours,All Levels,"[python programming, data science, theoretical...",udemy,0
4,React - The Complete Guide 2023 (incl. React R...,4.6,199663,74.5 total hours,All Levels,[react],udemy,0
...,...,...,...,...,...,...,...,...
19510,Explaining the Core Theories of Econometrics,4.2,1045,4 total hours,Beginner,[econometrics],udemy,1
19511,Construction Methodology Basics in Civil Engin...,4.6,1025,46 total hours,All Levels,"[estimation, video]",udemy,0
19512,Udemy Masters 2016: Online Course Creation - U...,4.1,1021,28 total hours,All Levels,[customer success],udemy,0
19513,Aerospace Engineering: Aircraft Systems and Av...,4.4,1001,2.5 total hours,All Levels,[internet of things],udemy,0
19514,Deutsch Intensiv - Intensive German Course for...,4.8,996,10.5 total hours,Beginner,[internet of things],udemy,1

In [158]:
def extract_hours(duration_str):
    match = re.search(r'(\d+\.?\d*)', duration_str)
    if match:
        return float(match.group(1))
    return None

udemy_v1["duration_hours"] = udemy_v1["duration"].apply(extract_hours)

In [159]:
udemy_v1

,course_title,rating,review_count,duration,level,skills_list,platform,level_num,duration_hours
0,The Complete Python Bootcamp From Zero to Hero...,4.6,486391,22 total hours,All Levels,[python programming],udemy,0,22.0
1,The Complete 2023 Web Development Bootcamp,4.7,338555,63 total hours,All Levels,"[javascript, html and css, react, postgresql]",udemy,0,63.0
2,The Web Developer Bootcamp 2023,4.7,266527,74 total hours,All Levels,"[javascript, html and css, react, internet of ...",udemy,0,74.0
3,100 Days of Code: The Complete Python Pro Boot...,4.7,251585,58 total hours,All Levels,"[python programming, data science, theoretical...",udemy,0,58.0
4,React - The Complete Guide 2023 (incl. React R...,4.6,199663,74.5 total hours,All Levels,[react],udemy,0,74.5
...,...,...,...,...,...,...,...,...,...
19510,Explaining the Core Theories of Econometrics,4.2,1045,4 total hours,Beginner,[econometrics],udemy,1,4.0
19511,Construction Methodology Basics in Civil Engin...,4.6,1025,46 total hours,All Levels,"[estimation, video]",udemy,0,46.0
19512,Udemy Masters 2016: Online Course Creation - U...,4.1,1021,28 total hours,All Levels,[customer success],udemy,0,28.0
19513,Aerospace Engineering: Aircraft Systems and Av...,4.4,1001,2.5 total hours,All Levels,[internet of things],udemy,0,2.5
19514,Deutsch Intensiv - Intensive German Course for...,4.8,996,10.5 total hours,Beginner,[internet of things],udemy,1,10.5

In [161]:
udemy_v1.isna().sum()

course_title      0
rating            0
review_count      0
duration          0
level             0
skills_list       0
platform          0
level_num         0
duration_hours    0
dtype: int64

In [162]:
try:
    udemy_v1 = udemy_v1.drop(['level','duration'],axis=1)
except Exception as ex:
    print("Data has been already processed")
udemy_v1

,course_title,rating,review_count,skills_list,platform,level_num,duration_hours
0,The Complete Python Bootcamp From Zero to Hero...,4.6,486391,[python programming],udemy,0,22.0
1,The Complete 2023 Web Development Bootcamp,4.7,338555,"[javascript, html and css, react, postgresql]",udemy,0,63.0
2,The Web Developer Bootcamp 2023,4.7,266527,"[javascript, html and css, react, internet of ...",udemy,0,74.0
3,100 Days of Code: The Complete Python Pro Boot...,4.7,251585,"[python programming, data science, theoretical...",udemy,0,58.0
4,React - The Complete Guide 2023 (incl. React R...,4.6,199663,[react],udemy,0,74.5
...,...,...,...,...,...,...,...
19510,Explaining the Core Theories of Econometrics,4.2,1045,[econometrics],udemy,1,4.0
19511,Construction Methodology Basics in Civil Engin...,4.6,1025,"[estimation, video]",udemy,0,46.0
19512,Udemy Masters 2016: Online Course Creation - U...,4.1,1021,[customer success],udemy,0,28.0
19513,Aerospace Engineering: Aircraft Systems and Av...,4.4,1001,[internet of things],udemy,0,2.5
19514,Deutsch Intensiv - Intensive German Course for...,4.8,996,[internet of things],udemy,1,10.5

In [164]:
#Normalization of the column names
try:
    udemy_v1 = udemy_v1.rename(
        columns={
            "level_num": "level",
            "duration_hours": "duration"
        }
    )
except:
    print("columns has been changing")
udemy_v1

,course_title,rating,review_count,skills_list,platform,level,duration
0,The Complete Python Bootcamp From Zero to Hero...,4.6,486391,[python programming],udemy,0,22.0
1,The Complete 2023 Web Development Bootcamp,4.7,338555,"[javascript, html and css, react, postgresql]",udemy,0,63.0
2,The Web Developer Bootcamp 2023,4.7,266527,"[javascript, html and css, react, internet of ...",udemy,0,74.0
3,100 Days of Code: The Complete Python Pro Boot...,4.7,251585,"[python programming, data science, theoretical...",udemy,0,58.0
4,React - The Complete Guide 2023 (incl. React R...,4.6,199663,[react],udemy,0,74.5
...,...,...,...,...,...,...,...
19510,Explaining the Core Theories of Econometrics,4.2,1045,[econometrics],udemy,1,4.0
19511,Construction Methodology Basics in Civil Engin...,4.6,1025,"[estimation, video]",udemy,0,46.0
19512,Udemy Masters 2016: Online Course Creation - U...,4.1,1021,[customer success],udemy,0,28.0
19513,Aerospace Engineering: Aircraft Systems and Av...,4.4,1001,[internet of things],udemy,0,2.5
19514,Deutsch Intensiv - Intensive German Course for...,4.8,996,[internet of things],udemy,1,10.5

In [165]:
udemy_v1.to_csv('udemy-v2.csv', index=False)